
workflows:
  android_ios_build:
    name: Android & iOS Build
    environment:
      flutter: stable
    scripts:
      - name: Generate platforms & fetch deps
        script: |
          flutter create .
          flutter pub get
      - name: Generate icons & splash
        script: |
          dart run flutter_launcher_icons
          dart run flutter_native_splash:create
      - name: Patch Android 13+ notifications permission (optional)
        script: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          if ! grep -q "POST_NOTIFICATIONS" "$MANIFEST"; then
            sed -i 's#</manifest>#  <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>\n</manifest>#' "$MANIFEST"
          fi
      - name: Set appId & compile settings
        script: |
          GRADLE="android/app/build.gradle"
          sed -i 's/applicationId ".*"/applicationId "com.example.pet_nutrition"/' "$GRADLE" || true
      - name: Build Android debug APK
        script: |
          flutter build apk --debug
      - name: Build Android Play Store AAB
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
      - build/app/outputs/bundle/release/app-release.aab
