
workflows:
  android_build:
    name: Android Build
    environment:
      flutter: stable
    scripts:
      - name: Ensure platforms & deps
        script: |
          if [ ! -d "android" ]; then
            flutter create .
          fi
          flutter pub get
      - name: Generate app icon & splash
        script: |
          dart run flutter_launcher_icons
          dart run flutter_native_splash:create
      - name: Patch Android Manifest (POST_NOTIFICATIONS for Android 13+)
        script: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          if ! grep -q "POST_NOTIFICATIONS" "$MANIFEST"; then
            sed -i 's#</manifest>#  <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>\n</manifest>#' "$MANIFEST"
          fi
      - name: Build debug APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

  play_release:
    name: Play Store Release
    environment:
      flutter: stable
    scripts:
      - name: Ensure platforms & deps
        script: |
          if [ ! -d "android" ]; then
            flutter create .
          fi
          flutter pub get
      - name: Generate icon & splash
        script: |
          dart run flutter_launcher_icons
          dart run flutter_native_splash:create
      - name: Patch Android Manifest (POST_NOTIFICATIONS for Android 13+)
        script: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          if ! grep -q "POST_NOTIFICATIONS" "$MANIFEST"; then
            sed -i 's#</manifest>#  <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>\n</manifest>#' "$MANIFEST"
          fi
      - name: Build AAB release
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
