workflows:
  android-workflow:
    name: Build Android App
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      java: 17
    scripts:
      - name: Create missing Android/iOS folders
        script: |
          if [ ! -d "android" ]; then
            echo "Android folder missing, generating..."
            flutter create .
          fi
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

