
name: pet_nutrition_app
description: Pet Nutrition – Care & Tips
version: 1.1.0+2

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.2
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/splash.png

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#F7FAF8"
  color_dark: "#121212"
  image: assets/images/splash.png
  android_12:
    image: assets/images/splash.png
    color: "#F7FAF8"
    color_dark: "#121212"
